# Minimal starship config
format = """
$directory$git_branch$git_status
$character"""

[directory]
truncation_length = 3
truncation_symbol = ".../"
format = "[$path]($style) "
style = "cyan"

[git_branch]
format = "[$branch]($style) "
style = "purple"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "yellow"

[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"

[username]
disabled = true
[hostname]
disabled = true
[time]
disabled = true
